#!/usr/bin/env python3
"""Tiny learning generator for EcuC_Cfg.h.

This is not an AUTOSAR ARXML generator. It only converts the learning JSON
configuration into a small C header so the hardware mapping can be changed
without editing application code.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "config" / "hardware_config.json"
OUT = ROOT / "generated" / "include" / "EcuC_Cfg.h"


def main() -> None:
    data = json.loads(CONFIG.read_text(encoding="utf-8"))
    cycle_ms = int(data["project"]["cycle_ms"])
    dio_channels = data["dio"]["channels"]
    led = next(ch for ch in dio_channels if ch["name"] == "DIO_CH_LED1")

    text = f"""#ifndef ECUC_CFG_H
#define ECUC_CFG_H

/* Auto-generated by tools/generate_from_config.py from config/hardware_config.json. */

#define ECUC_MAIN_FUNCTION_PERIOD_MS    ({cycle_ms}u)

#define ECUC_DIO_CHANNEL_LED1           ({int(led['id'])}u)
#define ECUC_DIO_LED1_PORT_NAME         \"{led['port']}\"
#define ECUC_DIO_LED1_PIN_NUMBER        ({int(led['pin'])}u)
#define ECUC_DIO_LED1_ACTIVE_HIGH       ({1 if bool(led['active_high']) else 0}u)

#endif /* ECUC_CFG_H */
"""
    OUT.write_text(text, encoding="utf-8")
    print(f"generated: {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
